### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by ghost** [baibaratsky/php-mailgun#16] opened 2016-10-24 17:55 UTC
I ran composer, I got a bunch of files in /vendor/baibaratsky/php-mailgun

But I am baffled by the example to get started.
"It's pretty easy..."
No other composer package requires me to include an autoloader,
and all other Yii2 packages have namespaces (this one does not).

My IDE is telling me that MailgunApi is not found/defined.
I don't know what to write for the "use" statement.
The example makes no sense to me because  Yii2 already includes ../../vendor/autoload.php in the entry script.

**Comment by baibaratsky** [comment] 2016-10-24 18:21
Composer requires to include autoloader by design. ;) https://getcomposer.org/doc/01-basic-usage.md#autoloading

For sure you don’t have to include composer‘s autoload.php in Yii2. Not all PHP users use Yii2, so the first example is not for Yii2 (but it will work in Yii2).

It’s not a Yii2 package by origin. It‘s a library that requires PHP 5.2, so it can‘t use namespaces.
But you can use it in Yii2 as well. Config for Yii2 should look like:
```php
        'mailgun' => [
            'class' => '\MailgunYii2',
            'domain' => 'some.domain',
            'key' => 'your_key',
            'viewPath' => '@common/views/mail', // if you need it
            'fromAddress' => 'some_guy@some.domain',
            'fromName' => 'Some Guy',
        ],
```
And a code to send a message:
```php
        /** @var \MailgunMessageYii2 $message */
        $message = Yii::$app->mailgun->newMessage();
        $message->setSubject('Foo');
        $message->addTo('some_user@of.my.app');
        $message->setText('It’s working!');
        Yii::$app->mailgun->sendMessage($message);
```

**Comment by santhosh-trillionthoughts** [comment] 2023-12-24 00:18
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Closed as completed** 2023-12-24 12:26 UTC
